### ISSUE TITLE
dp doesn't deploy the branch you tell it to!

### ISSUE THREAD

**Issue by ian-ross** [memcachier/dp#18]
You can give `dp deploy` a branch or tag name to deploy, but it ignores it and deploys whatever you have checked out!  This is BAD BAD BAD!

**Comment by saschat** [comment]
Actually, it also includes local changes.

**Comment by dterei** [comment]
Wow! What a world :) Haha local changes too!

**Comment by ian-ross** [comment]
I think what happened is that in the past, `dp` was always used in a context where you checked out the version you wanted to deploy, then you ran `dp`.  Now that we're trying to deploy from tags, there's no guarantee that the local repo is actually checked out to that version before running `dp`.  That's a good reason for the "not deploying branches" thing, but there's no excuse for the local changes problem!  That just makes it really hard to do repeatable deployments.  I'm going to change the way this works to make it a bit more robust (and so it does what you tell it to!).

**Comment by dterei** [comment]
Actually, I think I probably introduced the bug when I changed `dp` to not use `git-archive` as it doesn't support sub-modules.
