### ISSUE TITLE
Restrict log sizes

### ISSUE THREAD

**Issue by dterei** [memcachier/dp#4]
Logs can grow unbounded and will eventually cause issues.

**Comment by dterei** [comment]
daemontools has `multilog` just for this purpose.

**Comment by alevy** [comment]
Yes, and actually the default configuration of daemontools obviates this completely + adds other nice features like timestamps etc

**Comment by dterei** [comment]
Sorry, what do you mean by the default configuration?

**Comment by alevy** [comment]
You're not missing something, but that's not what I meant exactly. Basically, daemontools is _meant_ to be run using `supervise`, which watches a top-level directory for new/changes-to app directories and does all this "for you". It means starting daemontools differently from how we are right now.

`multilog`, of course, might work as is for now.

**Comment by dterei** [comment]
PR #7 fixes this.
